---
title: "MARKOV CHAIN (1)"
author: "NGUYEN NGOC PHUNG"
date: "10/20/2020"
output:
  word_document: default
  html_document: default
---
## MARKOV CHAIN SIMULATION

#### Simulation: a path of length 10 for Channel Market, given that X_0 = 1
```{r}
#First, we make a Markov Chain path function knowing state set S, transition matrix P, length of path n, initial position X0
MarKov_Chain_Path<-function(P,S,X0,n)
{
  Path<-numeric(n+1)
  Path[1]<-X0
  for(i in 2:(n+1))
  {
    row<-match(Path[i-1],S)
    Path[i]<-sample(S,1,prob=P[row,])
  }
  return(Path)
}

# We know the transition matrix P of channel market is as follow @-@
P<-matrix(c(0.8,0.1,0.2,0.9),2,2)
dimnames(P)<-list(c("Channel 1","Channel 2"),c("Channel 1","Channel 2"))
P
#So then we create a path of length 10 with state set S=(1,2) and X0=1 *-*
S<-c(1,2)
MarKov_Chain_Path(P,S,1,10)

```

## EXTRA INTERST
#### Simulate 10000 paths of previous simulation, check whether Pr(X10=i|X0=1) is consistent with 10-steps transition matrix 
```{r}
# we need to create a function for matrix multiplication @-@
matrixpower <- function(mat,k) {
	if (k == 0) return (diag(dim(mat)[1])) 
	if (k == 1) return(mat)
	if (k > 1) return( mat %*% matrixpower(mat, k-1))
}

#So the 10-steps transition matrix for P(10) is as the following:
P10<-matrixpower(P,10)
P10

#now, we simulate 10000 paths of Markov Chain above given X0=1 @-@
Path_1<-matrix(0,10000,11)
for(i in 1:10000)
{
  Path<-MarKov_Chain_Path(P,S,1,10)
  for(j in 1:11)
  {
    Path_1[i,j]<-Path[j]
  }
}
#First 10 rows of Path_1 is
Path_1[1:10,]

#So now I find the probability that X10=1 and X10=2 given X0=1
X10<-Path_1[,11]
X10_1<-0
X10_2<-0
for(i in 1:10000)
{
  if(X10[i]==1) {X10_1<-X10_1+1}
  else {X10_2<-X10_2+1}
}

#Probability
X10_1/10000
X10_2/10000

#So this probability is near to the true probability P(X10=1|X0=1)=0.3521650, P(X10=2|X0=1)=0.6478350 *-*

```