---
title: "MARKOV CHAIN (SUNDAY)"
author: "NGUYEN NGOC PHUNG"
date: "10/24/2020"
output: html_document
---
### EXAMPLE 1 (ATTENDDING CLASS)



#### Alice is taking a probability class and in each week she can be either up-to-date or she may have fallen behind. If she is up-to-date in a given week, the probability that she will be up-to-date (or behind) in the next week is 0.8 (or 0.2, respectively). If she is behind in the given week, the probability that she will be up-to-date (or behind) in the next week is 0.6 (or 0.4, respectively). We assume that these probabilities do not depend on whether she was up-to-date or behind in previous weeks, so the problem has the typical Markov chain character (the future depends on the past only through the present).



#### QUESTION 1: create the state space S and transition matrix P, draw transition diagram (*)

#### QUESTION 2: create a path of length 10 given X0=1

#### QUESTION 3: create 10 paths of length 10 given P(X0=1)=0.6, P(X0=2)=0.4

#### QUESTION 4: create a function to generate 1 path of any length n for any transition matrix. Then create a path of length 100 in this example

#### QUESTION 5: create 100 paths of length 10 given P(X0=1)=0.6, P(X0=2)=0.4

#### QUESTION 6: find 2-step and 3-step transition matrix P2, P3 (*)

#### QUESTION 7: find 100-step transition matrix P100





### EXAMPLE 2:(FLY AND SPIDER)


####  A fly moves along a straight line in unit increments. At each time period, it moves one unit to the left with probability 0.3, one unit to the right with probability 0.3, and stays in place with probability 0.4, independently of the past history of movements. A spider is lurking at positions 1 and m: if the fly lands there, it is captured by the spider, and the process terminates. We want to construct a Markov chain model, assuming that the fly starts in one of the positions 2,...,m − 1.



#### Given initially, the fly is equally positioned at any state

#### QUESTION 1: Let m=5, find P,P3 and S. draw transition diagram (*)

#### QEUSTION 2: create 10 paths of length 20 for m=5

#### QUESTION 3: Let m be any number of the set {5,12,15,20}.create 20 paths of length 20

#### QUESTION 4: for m=5, find P(X0=2,X1=3,X2=4,X3=4,X4=3) (*)

#### QUESTION 5: for m=5, find P(X1=3,X2=4,X3=4,X4=3|X0=2) (*)

#### QUESTION 6: for m=5, find P(X3=2,X5=3,X9=4,X10=4,X11=3), P(X2=4,X3=5), P(X4=2,X8=4,X10=3) (*)

#### QUESTION 7: for m=5, find P(X2=3,X5=4,X7=4,X10=3|X1=2), P(X3=2,X5=4,X8=5|X0=1) (*)

#### QUESTION 8: for m=5, find P(x2=3), P(X3=2), P(X10=4),P(X20=1) (*)

#### QUESTION 9: simulate 10,000 paths of length 20 in order to check whether P(x2=3), P(X3=2), P(X10=4),P(X20=1) (calculated in Q8) is consistent with the simulation 

#### QUESTION 10: simulate 10,000 paths of length 20 in order to check whether P(X3=2,X5=3,X9=4,X10=4,X11=3), P(X2=4,X3=5), P(X4=2,X8=4,X10=3) (calculated in Q6) is consistent with the simulation

#### QUESTION 11: simulate 10,000 paths of length 20 in order to check whether P(X2=3,X5=4,X7=4,X10=3|X1=2), P(X3=2,X5=4,X8=5|X0=1) (calculated in Q7) is consistent with the simulation

#### QUESTION 12: for m=5, find E[X5], E[X7], E[X10], VAR[X3],VAR[X5] (*)

#### QUESTION 13: find P10, P50 and P100





### EXAMPLE 3: FROG PROBLEM



#### QUESTION 1: Find P,P3 and S. (*)

#### QUESTION 2: Find the PMF of X3, X5 (*)

#### QUESTION 3: Find A(1),A(2), A(3), A(4), A(5) (**)

#### QUESTION 4: Find P50, P100, P150


#### State 6 appear *-*

#### Find P and S (*)

#### QUESTION 5: Find A(1),A(2), A(3), A(4), A(5), A(6) (**)

#### QUESTION 6: Find P50, P100, P150
















