---
title: "QUIZ SIMULATION"
author: "NGUYEN NGOC PHUNG"
date: "12/26/2020"
output:
  word_document: default
  html_document: default
---
### QUESTION 1
```{r}
# (QUESTION A)
#Function of Brownian motion path
Path_way<- function(n,t)
{
  Path<-c(0,cumsum(rnorm(n,0,sqrt(t/n))))
  return(Path)
}

# Plot the path of Brownian motion
n<-10000
t<-1
P<-Path_way(n,t)
step<-seq(0,1,length=n+1)
plot(step,P, type="l")

# (QUESTION B)

Xt<-t-(2*seq(0,t-t/n,t/n))

# Function for Path Riemann sum (left-endpoint)
left_endpoint<- function(n,integrand,integrator)
{
  #integrand is a vector with length n contain all value of f(xi-1) *-*
  #let's product be a vector contain f(xi-1)*integrator(x) for i in 1 to n
  product<-numeric(n)
  for(i in 1:n)
  {
    product[i]<-integrand[i]*(integrator[i+1]-integrator[i])
  }
  sum<-sum(product)
  return(sum)
}

Path_It<-numeric(n)
for(i in 1:n)
{
  Path_It[i]<-left_endpoint(i,Xt[1:i],P[1:(i+1)])
}

step<-seq(1/n,1,1/n)
plot(step,Path_It, type="l")

# Plot both Brownian and Ito integral in same graph
library(ggplot2)
x=seq(0,1-1/10000,1/10000)

combine <- data.frame(x,P[1:10000],Path_It)
ggplot(combine, aes(x)) +                    # basic graphical object
  geom_line(aes(y=P[1:10000]), colour="red") +  # first layer
  geom_line(aes(y=Path_It), colour="darkmagenta")
```

### QUESTION 2:
```{r}
# Distribution of I1
n<-1000
t<-1
I1<-numeric(10000)
for( i in 1:10000)
{
  P<-Path_way(1000,1)
  Xt<-1-(2*seq(0,1-1/1000,1/1000))
  I1[i]<-left_endpoint(1000,Xt,P)
}
I1[1:10]
mean(I1)
var(I1)
hist(I1,main="Distribution of I1",col="blue",breaks = 100 )

```