---
title: "ASSIGNMENT 3-SIMULATION RANDOM PROCESS"
author: "NGUYEN NGOC PHUNG"
date: "10/9/2020"
output:
  word_document: default
  html_document: default
---
## QUESTION 1

### A path S0, S1, ..., S5 of stock price in binomial asset pricing model (set up input parameters by yourself)

```{r}
#first we create a function for stock price @-@
S<-function(s0,u,p,n)
{
  #s0 is initial price,u is up factor, p is p(H), n is periods
  price<-numeric(n+1)
  price[1]<-s0
  for (i in 1:n)
  {
    Berno<-rbinom(1,1,p)
    if(Berno==1) {price[i+1]<-price[i]*u} else {price[i+1]<-price[i]/u}
  }
  return(price)
}
#Let So=5, u=2, d=0.5, p=2/3, q=1/3
S(5,2,2/3,5)
```

## QUESTION 2

### A path of symmetric random walk M0, M1,..., Mn for n = 10

```{r}
#first we create a function for random walk @-@
RW<-function(p,n)
{
  M<-numeric(n+1)
  M[1]<-0
  for(i in 1:n)
  {
    vector<-c(1,-1)
    x<-sample(vector,1,prob=c(p,1-p))
    M[i+1]<-M[i]+x
  }
  return(M)
}
RW(0.5,10)
```

## QUESTION 3

### Repeat part b) 10^3 times. Plot histogram for Mn. Based on histogram, what can you say about the probability mass function of Mn

```{r}
data<-matrix(0,1000,11)
dimnames(data)<-list(1:1000,c("M0","M1","M2","M3","M4","M5","M6","M7","M8","M9","M10"))
for(i in 1:1000)
{
  M<-RW(0.5,10)
  for(j in 1:11)
  {
    data[i,j]<-M[j]
  }
}
#So the first 10 rows of data look like following:
data[1:10,]
#So the histogram of Sn look as the following
hist(data[,11],col="blue",main="HISTOGRAM OF Sn")
#So we can clearly see that the distribution of Sn nearly normal distribution @-@

```





